blank_issues_enabled: false
contact_links:
  - name: "â“ Have a Question?"
    url: "https://github.com/Midnight-Pages/discussions"
    about: "For general questions, use GitHub Discussions instead of creating an issue."
